---
# task file for tomcat

- name: Install OpenJDK
  yum:
    name: java-1.8.0-openjdk-headless
    state: present
  when: tomcat_manage_java_pkg and ansible_facts['distribution'] == "CentOS"
- name: Install OpenJDK
  yum:
    name: openjdk-8-jdk
    state: present
  when: tomcat_manage_java_pkg and ansible_facts['distribution'] == "Ubuntu"
